image: docker:latest

services:
  - docker:dind

stages:
  - build-maven
  - build-docker

build-maven:
  stage: build-maven
  script:
    - 'docker run -v /builds/host-mc/Spring-CI-test:/root/app --name build-maven maven:3.5.0-jdk-8-alpine sh /root/app/maven-build.sh'
    - 'cp target/*.jar app.jar'
    - 'docker rm -f build-maven'
  artifacts:
    paths:
      - 'app.jar'

build-docker-master:
  stage: build-docker
  script:
    - 'docker build --pull -t $CI_REGISTRY_IMAGE .'
    - 'docker push $CI_REGISTRY_IMAGE'
  only:
    - master

build-docker:
  stage: build-docker
  script:
    - 'docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .'
    - 'docker push CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG'
  except:
    - master
