language: java
jdk: oraclejdk8
sudo: false
script: mvn clean verify
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
  
install: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn install -DskipTests=false -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

